version: '1'

services: 
  app-node: 
    image: calebgarrick/gdanaliterature
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 80:3000
    environment:
      - ORIGIN=http://localhost:80