name: Trigger auto deployment for gdanaliterature

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gdanaliterature-AutoDeployTrigger-b1f43d76-04b7-4353-a371-60e008761527.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GDANALITERATURE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.GDANALITERATURE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GDANALITERATURE_REGISTRY_PASSWORD }}
          containerAppName: gdanaliterature
          resourceGroup: gdanaliterature_group
          imageToBuild: calebgarrick/gdanaliterature:${{ github.sha }}
          dockerfilePath: Dockerfile

     

